### ISSUE TITLE
The latest production release of your project contains fatal errors.

### ISSUE THREAD

**Issue by 1p22geo** [PiotrSzczepanski8/konieczny-gra#1]
After visiting the [main page](https://piotrszczepanski8.github.io/konieczny-gra/) the game is not playable, the submit button does nothing but throwing an error.

I am going to open a pull request proposing changes pretty soon.
Attaching resources:

Screenshot: 
![screenshot](https://github.com/PiotrSzczepanski8/konieczny-gra/assets/113300767/dd08cc49-3db2-4bfe-be76-cb3df6792be9)

Browser error log:
```
favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
(anonymous) @ main.js:11
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
(anonymous) @ main.js:11
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)
main.js:11 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at HTMLFormElement.<anonymous> (main.js:11:13)

```

**Comment by 1p22geo** [comment]
After analysing the code I found out it's about the code expecting a local storage item named `names` to already exist, and be JSON-parse'able. If no local storage item exists, it's impossible to parse it, since JSON-parsing doesn't give an array.

I am working on a fix which will be submitted soon.

**Comment by 1p22geo** [comment]
Reproduction steps:
1. Open the main page (index.html)
2. Try submitting the form normally
3. Open the browser devtools and in the `application` tab, delete all local storage data.
    - [tutorial](https://leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/)
 4. Submit the form once again and witness the error!

**Comment by 1p22geo** [comment]
The PR is open, please approve and merge.
